version: "3.2"

services:

  redis:

    image: "redis:alpine"

    command: 
      - 'redis-server'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--port 5000'
      - '--appendonly yes'

    ports:
      - "5000:5000"

    volumes:
      - ./redis-data:/data
  
  mimic-bot:
    
    environment:
      - TELEGRAM_BOT_TOKEN=
      - REDIS_ADDR=redis://redis:5000

    image: "risboo6909/mimic-bot"
